2024-04-11 18:30:04,546 - INFO - Connected to COM7 at 19200 baud rate.
2024-04-11 18:30:13,103 - INFO - Raw data received: 19 H34T36
2024-04-11 18:30:15,814 - ERROR - Error inserting data: 
Traceback (most recent call last):
  File "c:\Users\mathi\Desktop\CPE 4-ETI\Projet Transversal\Appli WEB\src\python\script.py", line 40, in insert_data
    conn = psycopg2.connect(DB_CONNECTION)
  File "C:\Users\mathi\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError
2024-04-11 18:38:53,259 - INFO - Program terminated by user.
2024-04-11 18:38:53,268 - INFO - Serial connection closed.
2024-04-11 18:38:59,527 - INFO - Connected to COM7 at 19200 baud rate.
2024-04-11 18:39:03,232 - INFO - Raw data received: 19 H34T36
2024-04-11 18:39:05,933 - ERROR - Error inserting data: 
Traceback (most recent call last):
  File "c:\Users\mathi\Desktop\CPE 4-ETI\Projet Transversal\Appli WEB\src\python\script.py", line 40, in insert_data
    conn = psycopg2.connect(DB_CONNECTION)
  File "C:\Users\mathi\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError
2024-04-11 18:43:12,131 - INFO - Program terminated by user.
2024-04-11 18:43:12,148 - INFO - Serial connection closed.
2024-04-11 18:43:13,875 - INFO - Connected to COM7 at 19200 baud rate.
2024-04-11 18:43:17,914 - INFO - Raw data received: 19 H34T36
2024-04-11 18:43:20,630 - ERROR - Error inserting data: 
Traceback (most recent call last):
  File "c:\Users\mathi\Desktop\CPE 4-ETI\Projet Transversal\Appli WEB\src\python\script.py", line 40, in insert_data
    conn = psycopg2.connect(DB_CONNECTION)
  File "C:\Users\mathi\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError
2024-04-11 18:47:30,473 - INFO - Program terminated by user.
2024-04-11 18:47:30,482 - INFO - Serial connection closed.
2024-04-11 18:47:34,237 - INFO - Connected to COM7 at 19200 baud rate.
2024-04-11 18:47:37,294 - INFO - Raw data received: 19 H34T36
2024-04-11 18:47:40,011 - ERROR - Error inserting data: 
Traceback (most recent call last):
  File "c:\Users\mathi\Desktop\CPE 4-ETI\Projet Transversal\Appli WEB\src\python\script.py", line 40, in insert_data
    conn = psycopg2.connect(DB_CONNECTION)
  File "C:\Users\mathi\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError
2024-04-16 14:00:40,059 - INFO - Connected to COM7 at 19200 baud rate.
2024-04-16 14:00:45,758 - INFO - Raw data received: 19 H34T36
2024-04-16 14:00:57,540 - ERROR - Error inserting data: 
Traceback (most recent call last):
  File "c:\Users\mathi\Desktop\CPE 4-ETI\Projet Transversal\Appli WEB\src\python\script.py", line 40, in insert_data
    conn = psycopg2.connect(DB_CONNECTION)
  File "C:\Users\mathi\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError
2024-04-16 14:03:34,095 - INFO - Program terminated by user.
2024-04-16 14:03:34,103 - INFO - Serial connection closed.
2024-04-16 14:03:44,903 - INFO - Connected to COM7 at 19200 baud rate.
2024-04-16 14:03:49,717 - INFO - Raw data received: 19 H34T36
2024-04-16 14:03:49,738 - ERROR - Error inserting data: connection to server at "localhost" (::1), port 55432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
Traceback (most recent call last):
  File "c:\Users\mathi\Desktop\CPE 4-ETI\Projet Transversal\Appli WEB\src\python\script.py", line 40, in insert_data
    conn = psycopg2.connect(DB_CONNECTION)
  File "C:\Users\mathi\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 55432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

2024-04-16 14:06:11,831 - INFO - Program terminated by user.
2024-04-16 14:06:11,843 - INFO - Serial connection closed.
2024-04-16 14:06:15,952 - INFO - Connected to COM7 at 19200 baud rate.
2024-04-16 14:06:18,536 - INFO - Raw data received: 19 H34T36
2024-04-16 14:06:19,286 - ERROR - Error inserting data: permission denied for table measures
Traceback (most recent call last):
  File "c:\Users\mathi\Desktop\CPE 4-ETI\Projet Transversal\Appli WEB\src\python\script.py", line 42, in insert_data
    cur.execute("INSERT INTO measures (id_flower, measure_date, humidity, temperature) VALUES (%s, NOW(), %s, %s)",
psycopg2.errors.InsufficientPrivilege: permission denied for table measures

2024-04-16 14:09:29,415 - INFO - Program terminated by user.
2024-04-16 14:09:29,446 - INFO - Serial connection closed.
2024-04-16 14:09:36,028 - INFO - Connected to COM7 at 19200 baud rate.
2024-04-16 14:09:38,495 - INFO - Raw data received: 19 H34T36
2024-04-16 14:09:38,544 - ERROR - Error inserting data: permission denied for sequence measures_id_measure_seq
Traceback (most recent call last):
  File "c:\Users\mathi\Desktop\CPE 4-ETI\Projet Transversal\Appli WEB\src\python\script.py", line 42, in insert_data
    cur.execute("INSERT INTO measures (id_flower, measure_date, humidity, temperature) VALUES (%s, NOW(), %s, %s)",
psycopg2.errors.InsufficientPrivilege: permission denied for sequence measures_id_measure_seq

2024-04-16 14:13:02,339 - INFO - Program terminated by user.
2024-04-16 14:13:02,349 - INFO - Serial connection closed.
2024-04-16 14:14:37,326 - INFO - Connected to COM7 at 19200 baud rate.
2024-04-16 14:14:39,450 - INFO - Raw data received: 19 H34T36
2024-04-16 14:14:39,512 - INFO - Inserted: Flower ID 19, Humidity 34, Temperature 36
2024-04-16 14:21:59,498 - INFO - Raw data received: 1 H35T35
2024-04-16 14:21:59,499 - ERROR - Error parsing data: 1 H35T35
Traceback (most recent call last):
  File "c:\Users\mathi\Desktop\CPE 4-ETI\Projet Transversal\Appli WEB\src\python\script.py", line 29, in parse_data
    humidity = int(data[4:6])
ValueError: invalid literal for int() with base 10: '5T'
2024-04-16 14:21:59,518 - ERROR - Error processing data: 1 H35T35
Traceback (most recent call last):
  File "c:\Users\mathi\Desktop\CPE 4-ETI\Projet Transversal\Appli WEB\src\python\script.py", line 62, in <module>
    id_flower, humidity, temperature = parse_data(data)
  File "c:\Users\mathi\Desktop\CPE 4-ETI\Projet Transversal\Appli WEB\src\python\script.py", line 29, in parse_data
    humidity = int(data[4:6])
ValueError: invalid literal for int() with base 10: '5T'
2024-04-16 14:22:55,140 - INFO - Raw data received: 01 H35T35
2024-04-16 14:22:55,173 - INFO - Inserted: Flower ID 1, Humidity 35, Temperature 35
2024-04-16 14:25:39,089 - INFO - Program terminated by user.
2024-04-16 14:25:39,097 - INFO - Serial connection closed.
2024-04-16 14:25:41,471 - INFO - Connected to COM7 at 19200 baud rate.
2024-04-16 14:25:51,312 - INFO - Raw data received: 01 H35T35
2024-04-16 14:25:51,355 - INFO - Inserted: Flower ID 1, Humidity 35, Temperature 35
2024-04-16 14:28:30,395 - ERROR - Error opening the serial port: ClearCommError failed (OSError(22, 'Fonction incorrecte.', None, 1))
2024-04-16 14:28:30,410 - INFO - Serial connection closed.
2024-04-16 14:50:05,138 - INFO - Connected to COM7 at 19200 baud rate.
2024-04-16 14:50:08,689 - INFO - Raw data received: 01 H35T35
2024-04-16 14:50:08,744 - INFO - Inserted: Flower ID 1, Humidity 35, Temperature 35
2024-04-16 15:06:14,552 - INFO - Program terminated by user.
2024-04-16 15:06:14,567 - INFO - Serial connection closed.
2024-04-16 16:02:27,349 - INFO - Connected to COM7 at 19200 baud rate.
2024-04-16 16:02:33,279 - INFO - Raw data received: 01 H35T35
2024-04-16 16:02:33,374 - INFO - Inserted: Flower ID 1, Humidity 35, Temperature 35
2024-04-16 16:03:13,524 - INFO - Raw data received: 01 H50T10
2024-04-16 16:03:13,572 - INFO - Inserted: Flower ID 1, Humidity 50, Temperature 10
2024-04-16 16:07:19,843 - INFO - Raw data received: 01 H50T10
2024-04-16 16:07:19,905 - INFO - Inserted: Flower ID 1, Humidity 50, Temperature 10
2024-04-16 16:13:10,349 - ERROR - Error opening the serial port: ClearCommError failed (OSError(22, 'Fonction incorrecte.', None, 1))
2024-04-16 16:13:10,396 - INFO - Serial connection closed.
2024-05-06 19:42:14,761 - ERROR - Error opening the serial port: could not open port 'COM7': FileNotFoundError(2, 'Le fichier spécifié est introuvable.', None, 2)
2024-05-06 19:42:19,891 - ERROR - Error opening the serial port: could not open port 'COM7': FileNotFoundError(2, 'Le fichier spécifié est introuvable.', None, 2)
2024-05-06 19:42:40,006 - ERROR - Error opening the serial port: could not open port 'COM7': FileNotFoundError(2, 'Le fichier spécifié est introuvable.', None, 2)
2024-05-06 19:43:30,172 - ERROR - Error opening the serial port: could not open port 'COM7': FileNotFoundError(2, 'Le fichier spécifié est introuvable.', None, 2)
2024-05-06 19:54:10,451 - ERROR - Error opening the serial port: could not open port 'COM7': FileNotFoundError(2, 'Le fichier spécifié est introuvable.', None, 2)
2024-05-06 20:06:10,339 - INFO - Connected to COM2 at 19200 baud rate.
2024-05-06 20:06:29,912 - INFO - Raw data received: 01 H80T37L200
2024-05-06 20:06:29,960 - INFO - Inserted: Flower ID 1, Humidity 80, Temperature 37, Brightness 200
2024-05-06 20:13:41,571 - INFO - Raw data received: 01 H30T25L250
2024-05-06 20:13:41,594 - INFO - Inserted: Flower ID 1, Humidity 30, Temperature 25, Brightness 250
2024-05-06 20:17:29,441 - INFO - Program terminated by user.
2024-05-06 20:17:29,441 - INFO - Serial connection closed.
